name: 02. Orchestrate r35.2.1 pipeline

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

concurrency:
  group: orchestrate-r3521-${{ github.ref }}
  cancel-in-progress: false

jobs:
  dispatch-sequence:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build PyTorch r35.2.1
        uses: KalanaRatnayake/sequential-dispatcher@v1
        with:
          workflow_file: .github/workflows/r3521-pytorch.yml
          ref: main
          label: Build PyTorch r35.2.1

      - name: Build ROS Humble Core r35.2.1
        uses: KalanaRatnayake/sequential-dispatcher@v1
        with:
          workflow_file: .github/workflows/r3521-humblecore.yml
          ref: main
          label: Build ROS Humble Core r35.2.1

      - name: Build ROS Humble Base r35.2.1
        uses: KalanaRatnayake/sequential-dispatcher@v1
        with:
          workflow_file: .github/workflows/r3521-humblebase.yml
          ref: main
          label: Build ROS Humble Base r35.2.1

      - name: Build ROS + PyTorch Humble Core r35.2.1
        uses: KalanaRatnayake/sequential-dispatcher@v1
        with:
          workflow_file: .github/workflows/r3521-pytorch-humblecore.yml
          ref: main
          label: Build ROS + PyTorch Humble Core r35.2.1
