name: Jetson ROS Humble Pytorch r36.3.0

on:
  workflow_dispatch:

  workflow_run:
    workflows: [Jetson Pytorch r36.3.0]
    types:
      - completed

  push:
    branches: 
      - main
    paths:
      - ".github/workflows/r3630-pytorch-humble.yml"
      - "ros-pytorch/humble/r3630.Dockerfile"

  pull_request:
    branches: 
      - main
    paths:
      - ".github/workflows/r3630-pytorch-humble.yml"
      - "ros-pytorch/humble/r3630.Dockerfile"

env:
  REGISTRY: ghcr.io
  OWNER: kalanaratnayake
  IMAGE_NAME: jetson-ros-pytorch

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:

  build-and-push-image:
    if: ${{ github.event_name != 'workflow_run' }}
    runs-on: ubuntu-24.04-arm

    permissions:
      contents: write
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      # QEMU not required on native ARM runners

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        run: |
          docker login --username ${{ env.OWNER }} --password ${{ secrets.GH_PAT }} ghcr.io 
        # uses: docker/login-action@v3
        # with:
        #   registry: ${{ env.REGISTRY }}
        #   username: ${{ github.actor }}
        #   password: ${{ secrets.GITHUB_TOKEN }}

      - 
        name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./ros-pytorch/humble/r3630.Dockerfile
          push: true
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:humble-r36.3.0